### ISSUE TITLE
US7

### ISSUE THREAD

**Issue by Airglow98** [Airglow98/Capstone-Project#13]

**Comment by Airglow98** [comment]
## Value Proposition

**As a** user
**I want to** see my Library and Wishlist games after I switch a site
**so that** I do not have to click on them every time I start the app
​

## Description



![Image](https://github.com/Airglow98/Capstone-Project/assets/92044004/b6bb86a0-666d-4b96-a1bd-7efe15af1db9)


​

## Acceptance Criteria

- [ ] Wishlist games are shown in the wishlist area
- [ ] Library games are shown in the library area
      ​

## Tasks

- [ ] add local storage to save the states from different games ( I'm not sure how to do this exactly so I just add this task until I know more about the different Steps)
      ​

**Comment by Airglow98** [comment]
It's possible to enter the library and wishlist pages via the profilepage. The spotlightpage is just there to show how you can toggle the states.

**Comment by dimitriosxmi** [comment]
## LGTM very understandable US 🎉
