### ISSUE TITLE
US10

### ISSUE THREAD

**Issue by 4irgl0w** [Airglow98/Capstone-Project#19]
## Value Proposition

**As a** user
**I want to** upload a profile image
**so that** I see my own avatar/image
​

## Description

<img width="274" alt="Bildschirmfoto 2023-07-12 um 10 47 04" src="https://github.com/Airglow98/Capstone-Project/assets/92044004/391827c0-2cff-456c-a676-878a8865e021">​

## Acceptance Criteria

- [x] The uploaded Image do not get lost after a reload
- [x] The rest of the app looks like before
      ​

## Tasks

- [x] creata a branch 
- [x] use cloudinary to save the images
