### ISSUE TITLE
US3

### ISSUE THREAD

**Issue by Airglow98** [Airglow98/Capstone-Project#3]
## Value Proposition

**As a** user 
**I want to** use the searchbar
**so that** I can find one specific game
​

## Description

![Image](https://user-images.githubusercontent.com/92044004/248765295-c738fd08-0c48-47b5-898b-221a6235b8d4.png)

​

## Acceptance Criteria

- [ ] User can search a game via the searchbar
      ​

## Tasks

- [ ] create a searchbar
- [ ] filter the list of games
- [ ] if there is no result a "could not found this game" message appears

**Comment by actyvystom** [comment]
Hey Niklas, a nice one!
Please see some comments to consider:

Concerning your **value proposition**, you should keep away from technical language. Imagine your user does not know what a search bar is - try to think out of this point of view, so your value proposition would rather be something like
> As a user
> I want to be able to search for a game title
> so that I can find a game I am looking for

Concerning your **acceptance criteria** I suggest to bring more detail to it. Just some thoughts: 
- what happens exactly when the user enters a sarch term into the search field? 
- Will there be a button to trigger the search or will it run onChange of the field? 

Concerning your **task list**: also please add more detail about the the search functionality and 
your last entry in your task list is better put to the acceptance criteria.

Cheers, Thomas

**Comment by Airglow98** [comment]
Thanks again for your help. I did not think about the possibility that people do not know what a searchbar is. I'll try to keep explanations easier. I also added more steps for the acceptance criteria and the tasks.

**Comment by julialoeschel** [comment]
great. very strong story now! 
awesome 🐜
